services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - celery-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery-worker
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - celery-network

  flower:
    build:
      context: .
      dockerfile: Dockerfile.flower
    container_name: flower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    networks:
      - celery-network





networks:
  celery-network:
    driver: bridge
